### ISSUE TITLE
can you explain this repo's  principle?

### ISSUE THREAD

**Issue by guduxingzou** [sanshirookazaki/chat#1]
It is cool  .can you explain this repo's  principle?
I want to use it for my training data.
thanks!

**Comment by sanshirookazaki** [comment]
Thank you for your comment.
I made this with tutorial of Tensorflow as a reference. (sequence-to-sequence models)
In case of tutorial , English translate French.
My model is a chat machine that can learn conversation.

You need conversation  data of input and reply, split the data in two ,train and test.
You put the data in files below.
- train_data_in.txt
- train_data_out.txt
- test_data_in.txt
- test_data_out.txt

Please add line breaks a sentence, set parameters like batch_size , layer size and vocabulary size in translate.py.

Now you can train this model.
On the command line type:
python translate.py --data_dir datas --train_dir datas

at the appropriate time, Quit exit training.
On the command line type:
python translate.py --decode --data_dir datas --train_dir datas

so, you can chat with this machine.

**Comment by guduxingzou** [comment]
Thanks very much！
Is the data file model like this：
train_data_in :   how are you?
train_data_out:   I'm fine!

**Comment by sanshirookazaki** [comment]
That's good.
but , it reads word per space.
maybe you should add space in front of symbol .

**Comment by guduxingzou** [comment]
thanks！

**Comment by zhengsw** [comment]
how data  of input and reply i need  store in 
train_data_in.txt
train_data_out.txt
test_data_in.txt
test_data_out.txt

**Comment by zhengsw** [comment]
when can i quit exit training?
